inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - '**/*/*.rake'
    - 'config/initializers/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
  IgnoredMethods: ['describe', 'context', 'configure']

Style/FrozenStringLiteralComment:
  Enabled: false
